### ISSUE TITLE
PHP 8 Compatibility

### ISSUE THREAD

**Issue by rumcais** [Kdyby/Redis#101]
After running composer update in a nette project with PHP 8  I've got the following error:
`kdyby/redis v5.1.0 requires php ^7.1 -> your php version (8.0; overridden via config.platform, actual: 7.4.11) does not satisfy that requirement.`

**Comment by KacerCZ** [comment]
There is already PR for PHP 8 compatibility https://github.com/Kdyby/Redis/pull/100

**Comment by VBoss** [comment]
Merged - new release https://github.com/Kdyby/Redis/releases/tag/v5.2.0 please test in your application ;)
