### ISSUE TITLE
RedisException: Redis server went away after upgrade to v 6.0.0

### ISSUE THREAD

**Issue by zabous** [Kdyby/Redis#109]
After upgrade from v5.2.0 to v 6.0.0 - RedisException: Redis server went away
Same config as before (last php 8.0, last redis client, nette 3.0)

In RedisExtension.php there is protected function loadSession. 
$sessionConfig['host'] is set always to default '127.0.0.1' even if I have Redis in another container.

**Comment by jaroslavlibal** [comment]
I also tried to upgrade today and I am facing the same error. However, I haven't had time to investigate the cause yet.

**Comment by VBoss** [comment]
Could you send your neon config to reproduce this issue?

**Comment by jaroslavlibal** [comment]
```neon
redis:
    auth: "xxx"
    debugger: no
    host: redis
    journal: yes
    persistent: true
    session: {database: 1}
    storage: yes
```
But as I said, I haven't done any analysis on my side yet.

**Comment by zabous** [comment]
Linked pull request https://github.com/Kdyby/Redis/pull/110

**Comment by slepic** [comment]
Having the same issue. As workaround I pass host to session config as well as the parent config.

```
host: %redisHost%
session:
   host: %redisHost%
```

@VBoss Anyway, looks like a fix is ready, can you merge it, please?
