### ISSUE TITLE
Support for pipelining

### ISSUE THREAD

**Issue by TomasVotruba** [Kdyby/Redis#39]
Do you plan to support it?

I just tried to use it on pure `Redis` class and performance got **20x better**. See [source](http://odino.org/redis-slow-with-php-think-again/). 

Also [this issue](https://github.com/nicolasff/phpredis/issues/251) in phpredis is useful.

I found this disadvantage of pipelining:

*It's not that retrieval operations aren't working, it's just that you
are queueing them up in the pipeline which means that you won't be
able to get the results until you read the stream of replies back from
Redis. Pipelining can be applied only in certain scenarios, for
example you can't perform conditional operations while pipelining (at
least not without using a second connection).*

I tried to implement it but with no success.

**Comment by TomasVotruba** [comment]
I want this out of my issue list. Feel free to create new one.

**Comment by fprochazka** [comment]
Please do not close my issues. Nobody is forcing you to implement it.

**Comment by TomasVotruba** [comment]
It's in my issue list and I don't need it anymore. You're are forcing me to keep it there.

**Comment by fprochazka** [comment]
And you're making a mess in my issues...

**Comment by TomasVotruba** [comment]
Thank you
