### ISSUE TITLE
Remove dependency on nette/deprecated package

### ISSUE THREAD

**Issue by KacerCZ** [Kdyby/Redis#48]
This extension is dependent on package nette/deprecated. It would be useful to update it to use up-to-date class names.

I found `\Nette\Diagnostics\Debugger` instead of `\Tracy\Debugger` in `RedisSessionHandler`.

**Comment by fprochazka** [comment]
I have no idea what version have you installed, but this is not in master since this commit https://github.com/Kdyby/Redis/commit/000785f5385768eed876067c93fa2ae6887dadb7. If you find anything deprecated, please a pullrequest.
