### ISSUE TITLE
SessionHandler - setEX error on session.cookie_lifetime = 0

### ISSUE THREAD

**Issue by forrest79** [Kdyby/Redis#50]
If you have set configuration session.cookie_lifetime = 0, getTtl() return 0 and setEX try to write 0 for expiration, but redis can't handle this.

**Comment by forrest79** [comment]
Maybe use gc_maxlifetime if cookie_lifetime is 0?

**Comment by fprochazka** [comment]
I'm open to suggestions! Would be happy to accept a pullrq also :)

**Comment by forrest79** [comment]
I will definitely make a pullrq after we decide, how we handle this :-) For example Predis SessionHandler check only gc_maxlifetime or user defined value. For me this make sence. If cookie_lifetime is smaller than gc_maxlifetime, then use cookie_lifetime, if gc_maxlifetime is smaller than cookie_lifetime, then use cookie_lifetime and if cookie_lifetime is 0, then use gc_maxlifetime too. We can have session in redis longer than is neccesary, when user close browser before gc_maxlifetime, but I think, that we could life with it :-)

**Comment by fprochazka** [comment]
I suppose you're talking about the else branch, because [the `min()` behaviour is implemented here](https://github.com/Kdyby/Redis/blob/c000787e509c8ad0fb7b62ab170ca228bab52e9e/src/Kdyby/Redis/RedisSessionHandler.php#L87)

**Comment by fprochazka** [comment]
[The `min()` behaviour is implemented here](https://github.com/Kdyby/Redis/blob/c000787e509c8ad0fb7b62ab170ca228bab52e9e/src/Kdyby/Redis/RedisSessionHandler.php#L87), so I guess we just have to make it smarter to choose the min, but not if one of them is zero?

**Comment by forrest79** [comment]
Yes, that is what I am talking about :-) Maybe I am not so good to describe it in english :-) I don't know if gc_maxlifetime can be zero. Because if it can, I don't know what time return for setEx. If it can't I agreed with you to choose the min but not zero.

**Comment by forrest79** [comment]
Ok, I have tested it and gc_maxlifetime can be set to 0. I can't image what PHP do when gc_maxlifetime is 0, but we need to deside what to do, if gc_maxlifetime = 0 and also cookie_lifetime = 0. Return Nette deafult gc_maxlifetime (3 hours) or PHP default gc_maxlifetime (1440s)?

**Comment by fprochazka** [comment]
I would throw an exception if all the resulting time is 0, because that would be just stupid.

**Comment by fprochazka** [comment]
You can always change that for session in config and the sessionhandler in kdyby/redis should pick that up.

**Comment by fprochazka** [comment]
Fixed by https://github.com/Kdyby/Redis/pull/52
