### ISSUE TITLE
Problem with loading from cache

### ISSUE THREAD

**Issue by jakubkratina** [Kdyby/Redis#57]
Hi,

I`m trying to use Redis cache for address suggestion at Nette.

When I save `array` result like, where `$suggestions` is array:
```
$cache->save($key, Json::encode($suggestions), [
	Cache::TAGS    => [self::ADDRESS_SUGGESTION_KEY],
	Cache::EXPIRE  => self::ADDRESS_SUGGESTION_EXPIRATION,
	Cache::SLIDING => TRUE,
]);
``` 

and load them 
`$suggestions = $cache->load($key);`

I get array (count = 1) with index `0` and value:

`\x00\x00\x02\x12\x01>{"time":"0.84394800 1449592378","delta":31622400}\x00["Jind\xc5\x99icha Plachty, Praha, \xc4\x8cesk\xc3\xa1 repub...`

What are these chars `\x00\x00\x02\x12\x01>` for? I can`t unserialize, decode or do something else with them.

Don`t you know, where the problem is?

Thank you.

**Comment by wise007** [comment]
It looks like problem at rabbitMQ. Sorry :)

**Comment by wise007** [comment]
I thought that was problem at `RabbitMq`, but still not working.
