### ISSUE TITLE
PHP 7.2 - Cannot use 'Object' as class name as it is reserved

### ISSUE THREAD

**Issue by martinvenus** [Kdyby/Redis#75]
- bug report? yes
- feature request? no

### Description
 - PHP 7.2 uses "Object" as typehint (https://wiki.php.net/rfc/object-typehint).
 - Tested with docker image "php:7.2.0RC3-fpm".

**Comment by KacerCZ** [comment]
This will require Nette 2.4 and use `\Nette\SmartObject` trait instead of `\Nette\SmartObject`.

@fprochazka Do you have any plan to update this package and accept pending PRs?

**Comment by ondrakub** [comment]
@fprochazka Hi, is there a chance for the early support of php 7.2?

**Comment by enumag** [comment]
@martinvenus @KacerCZ @ondrakub Send a PR for 7.2. I'll merge it for you.

Pending PRs are mostly ourdated or failing. Feel free to ping me on any rebased and non-failing PRs.

**Comment by martinvenus** [comment]
https://github.com/Kdyby/Redis/pull/76

**Comment by enumag** [comment]
Fixed by #76.

**Comment by martinvenus** [comment]
Could someone (@KacerCZ, @ondrakub) please test current master? @enumag will then release new version (tag). For more info see https://github.com/Kdyby/Redis/pull/76.

**Comment by ondrakub** [comment]
@martinvenus @enumag testing all day and no problem found

**Comment by martinvenus** [comment]
I have made some tests and haven't found any problem. What about @KacerCZ?

**Comment by KacerCZ** [comment]
@martinvenus @enumag Works for me.

**Comment by enumag** [comment]
Here you go. Thank you all!

https://github.com/Kdyby/Redis/releases/tag/v4.0.0
