### ISSUE TITLE
Incompatible declarations of Redis::connect() and Redis::script()

### ISSUE THREAD

**Issue by jelen07** [Kdyby/Redis#78]
I have an issue on my environments. ATM I have Kdyby/Redis 4.0.0. and installed redis v4.0.6 (macOS) and I gets 2 errros:

```
PHP Warning: Declaration of Kdyby\Redis\Driver\PhpRedisDriver::connect($host, $port = NULL, $timeout = 0) should be compatible with Redis::connect($host, $port, $timeout = NULL, $retry_interval = NULL) in .../redis/src/Kdyby/Redis/Driver/PhpRedisDriver.php:21

PHP Warning: Declaration of Kdyby\Redis\Driver\PhpRedisDriver::script($command, $script = NULL) should be compatible with Redis::script($cmd, ...$args) in .../redis/src/Kdyby/Redis/Driver/PhpRedisDriver.php:21
```

On redis v4.0.0 (ubuntu) is it ok as on `v3.2.100` (windows).

Note that PHP Storm have another implementations :-/
```
public function connect( $host, $port = 6379, $timeout = 0.0, $reserved = NULL, $retry_interval = 0)
```

Related topis https://forum.nette.org/cs/29379-kompatibilita-kdyby-redis-connect

**Comment by enumag** [comment]
Kdyby/Redis is no longer actively developed. But if you send a pull request with a fix then I can merge it for you.

**Comment by KacerCZ** [comment]
@jelen07 Redis version is for server or PHP extension? Because this issue is related to changes in PHP extension.

**Comment by jelen07** [comment]
@KacerCZ I don't exactly know, what do you asking for.
- `Redis` is installed service on the server
- PHP extension is required to use `Redis`
- `Kdyby\Redis` overrides those methods, which have different parameters across versions `BC break`

**Comment by lukasojd** [comment]
+1

**Comment by vojtamares** [comment]
So theoreticaly this particular issue would be solved by updating the PhpRedisDriver::connect and PhpRedisDriver::script to correspond with current method of php's redis extension? or is this more to that. 

I am not saying a word about maintaining this repo, but just to fix this issue while it is still in use by many others.

**Comment by enumag** [comment]
Should be solved by https://github.com/Kdyby/Redis/pull/80.

**Comment by enumag** [comment]
Please test it and let me know if it's alright to make a stable release. Thanks!

**Comment by her-ur** [comment]
I tested it in our development environment and everything seems to be ok.
